# Generated by Django 5.1.6 on 2025-02-18 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('propertyType', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('floors', models.PositiveIntegerField()),
                ('coveredArea', models.CharField(max_length=30)),
                ('electricityStatus', models.CharField(max_length=30)),
                ('bathroomCount', models.PositiveIntegerField()),
                ('bedroomCount', models.PositiveIntegerField()),
                ('bookingAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Under Contract', 'Under Contract')], default='Available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('performance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('sales_closed', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tasks_completed', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='Unknown Buyer', max_length=100)),
                ('buyer_id', models.CharField(default='Unknown ID', max_length=100)),
                ('buyer_email', models.EmailField(blank=True, default='notprovided@example.com', max_length=254, null=True)),
                ('buyer_tel', models.CharField(default='Not Provided', max_length=20)),
                ('buyer_address', models.TextField(default='Not Provided')),
                ('payment_method', models.CharField(default='Cash', max_length=20)),
                ('seller_name', models.CharField(default='Unknown Seller', max_length=100)),
                ('seller_tel', models.CharField(default='Not Provided', max_length=20)),
                ('seller_email', models.EmailField(blank=True, default='notprovided@example.com', max_length=254, null=True)),
                ('seller_address', models.TextField(default='Not Provided')),
                ('ownership_verification', models.CharField(default='Pending Verification', max_length=100)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('title_insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('legal_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertylisting')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Task', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Overdue', 'Overdue')], max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
                ('predefined_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.predefinedtask')),
            ],
        ),
    ]
