# Generated by Django 5.1.6 on 2025-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250219_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='aggregate_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
