# Generated by Django 5.1.6 on 2025-02-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
