# Generated by Django 5.1.6 on 2025-02-18 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_task_title_delete_salesrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Salez',
        ),
    ]
