# Generated by Django 5.1.6 on 2025-02-19 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_propertylisting_bookingamount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancemetrics',
            name='aggregate_points',
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ownership_verification',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Loan', 'Loan'), ('Installments', 'Installments')], default='Cash', max_length=20),
        ),
    ]
