# Generated by Django 5.1.4 on 2025-01-24 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_propertylisting_status_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_status',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Successful', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
