# Generated by Django 5.1.4 on 2025-01-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_sale_profit_sale_transaction_status_alter_sale_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
