# Generated by Django 5.1.6 on 2025-02-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_performancemetrics_aggregate_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetrics',
            name='aggregate_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ownership_verification',
            field=models.CharField(default='Pending Verification', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
    ]
