# Generated by Django 5.1.6 on 2025-02-18 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_sale_salez'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(default='Unknown Buyer', max_length=100)),
                ('buyer_id', models.CharField(default='Unknown ID', max_length=100)),
                ('buyer_email', models.EmailField(blank=True, default='notprovided@example.com', max_length=254, null=True)),
                ('buyer_tel', models.CharField(default='Not Provided', max_length=20)),
                ('buyer_address', models.TextField(default='Not Provided')),
                ('payment_method', models.CharField(default='Cash', max_length=20)),
                ('seller_name', models.CharField(default='Unknown Seller', max_length=100)),
                ('seller_tel', models.CharField(default='Not Provided', max_length=20)),
                ('seller_email', models.EmailField(blank=True, default='notprovided@example.com', max_length=254, null=True)),
                ('seller_address', models.TextField(default='Not Provided')),
                ('ownership_verification', models.CharField(default='Pending Verification', max_length=100)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('title_insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('legal_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertylisting')),
            ],
        ),
    ]
