# Generated by Django 5.1.4 on 2025-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='bathroom_count',
            new_name='bathroomCount',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='bedroom_count',
            new_name='bedroomCount',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='booking_amount',
            new_name='bookingAmount',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='covered_area',
            new_name='coveredArea',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='electricity_status',
            new_name='electricityStatus',
        ),
        migrations.RenameField(
            model_name='propertylisting',
            old_name='property_type',
            new_name='propertyType',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Under Contract', 'Under Contract')], default='Available', max_length=20),
        ),
    ]
