# Generated by Django 5.1.6 on 2025-02-19 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_performancemetrics_aggregate_points_alter_sale_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sale')),
            ],
        ),
    ]
