# Generated by Django 5.1.6 on 2025-02-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_sale_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salez',
        ),
    ]
