# Generated by Django 5.1.6 on 2025-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_agentprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Agent', max_length=50),
        ),
    ]
